export interface CertificationProgram {
  id: string;
  title: string;
  category: string;
  categoryTag: string;
  provider: string;
  certType: string;
  duration: string;
  funding: string;
  quota: number;
  remainingQuota: number;
  coverImage: string;
  description: string;
  targetIndustry: string;
  benefits: string[];
  isOpen: boolean;
  location: string;
  batchNumber: string;
  schedule: string;
  registrationDeadline: string;
  requirements: string[];
  curriculum: { module: string; hours: string; description: string }[];
}

export const CERTIFICATION_PROGRAMS: CertificationProgram[] = [
  {
    id: 'prog-wld',
    title: 'Sertifikasi Juru Las 6G Pipa Bertekanan (SMAW & GTAW)',
    category: 'PENGELASAN',
    categoryTag: 'WELDING',
    provider: 'Balai Latihan Kerja Mimika & LSP Las Logam',
    certType: 'Sertifikat Kompetensi BNSP & Standar ASME IX',
    duration: '40 Hari • 160 Jam Pelatihan',
    funding: '100% Gratis (Dibiayai APBD Kab. Mimika)',
    quota: 25,
    remainingQuota: 6,
    coverImage: '/images/flyers/welding_flyer.jpg',
    description: 'Pelatihan teknik pengelasan pipa posisi 6G miring tetap menggunakan kombinasi GTAW Argon dan SMAW khusus jaringan konsentrator dan perpipaan tambang bertekanan tinggi.',
    targetIndustry: 'Kontraktor Migas, Konsentrator, Pabrik Smelter, & Petrosea',
    benefits: ['Asrama & Makan 3x Sehari', 'Uang Saku Bulanan', 'APD Standar Tambang Lengkap', 'Uji Kompetensi BNSP Gratis', 'Jalur Penyerapan Kerja Industri'],
    isOpen: true,
    location: 'Workshop Pengelasan BLK Kab. Mimika, Kuala Kencana',
    batchNumber: 'Batch IV / 2026',
    schedule: 'Senin - Jumat, 08.00 - 16.00 WIT',
    registrationDeadline: '15 Oktober 2026',
    requirements: [
      'Warga Negara Indonesia berdomisili di Kabupaten Mimika (KTP Mimika diutamakan)',
      'Usia minimal 18 tahun dan maksimal 35 tahun',
      'Pendidikan minimal SMK Jurusan Mesin/Teknik atau SMA Sederajat',
      'Sehat jasmani dan rohani, tidak buta warna (melampirkan surat dokter)',
      'Bersedia tinggal di asrama dan mengikuti pelatihan intensif sampai tuntas',
    ],
    curriculum: [
      { module: 'K3 & Regulasi Pengelasan Tambang', hours: '16 Jam', description: 'Standar keselamatan kerja gas bertekanan, hot work permit, dan proteksi asap radiasi busur api.' },
      { module: 'Pengelasan GTAW (Argon) Akar Pipa (Root Pass)', hours: '48 Jam', description: 'Teknik penetrasi tembus sempurna pipa 2-inch dan 6-inch schedule 40/80 tanpa cacat porositas.' },
      { module: 'Pengelasan SMAW Pengisian & Penutup (Capping)', hours: '56 Jam', description: 'Multi-layer pass elektroda Low Hydrogen E7018 posisi pipa 45 derajat miring tetap (6G).' },
      { module: 'Uji Non-Destructive Test (NDT) & Radiografi', hours: '20 Jam', description: 'Simulasi inspeksi X-Ray dan Liquid Penetrant Test sesuai standar ASME Boiler & Pressure Vessel Code.' },
      { module: 'Uji Kompetensi BNSP / Asesmen Akhir', hours: '20 Jam', description: 'Uji sertifikasi resmi oleh Asesor Lembaga Sertifikasi Profesi (LSP) Las Logam.' },
    ],
  },
  {
    id: 'prog-abt',
    title: 'Pelatihan Operator Excavator & Haul Truck Tambang',
    category: 'ALAT_BERAT',
    categoryTag: 'HEAVY_EQUIPMENT',
    provider: 'Balai Latihan Kerja Mimika & LSP Alat Berat',
    certType: 'SIO Aktif Kemenaker & BNSP Level 2',
    duration: '45 Hari • 180 Jam Pelatihan',
    funding: '100% Gratis (Dibiayai APBD Kab. Mimika)',
    quota: 30,
    remainingQuota: 8,
    coverImage: '/images/flyers/alat_berat_flyer.jpg',
    description: 'Pelatihan pengoperasian unit berat kelas tambang terbuka dengan kurikulum manuver lereng curam, bench loading excavator 30T+, pemeliharaan harian (P2H), dan protokol radio komunikasi pit.',
    targetIndustry: 'Kontraktor Penambangan Terbuka, Earthmoving, & Freeport Partner',
    benefits: ['Simulator 3D Caterpillar & Unit Asli', 'Surat Izin Operator (SIO) Kemenaker', 'Asuransi Peserta BPJS TK', 'Akomodasi & Makan 3x Sehari', 'Penyaluran Kerja ke Kontraktor'],
    isOpen: true,
    location: 'Training Ground Alat Berat BLK Mimika & PT KPI Area',
    batchNumber: 'Batch III / 2026',
    schedule: 'Senin - Sabtu, 07.30 - 15.30 WIT',
    registrationDeadline: '20 Oktober 2026',
    requirements: [
      'WNI berdomisili di Kabupaten Mimika (KTP / KK Mimika)',
      'Usia minimal 20 tahun dan maksimal 35 tahun',
      'Pendidikan minimal SMA / SMK Sederajat',
      'Memiliki SIM A / SIM B1 aktif (nilai tambah)',
      'Bebas dari pengaruh narkoba dan alkohol (tes urin di BLK)',
      'Tidak memiliki fobia ketinggian / ruang kemudi tertutup',
    ],
    curriculum: [
      { module: 'Pemeriksaan Harian & Keselamatan Operasi (P2H)', hours: '20 Jam', description: 'Prosedur walk-around inspection, pengecekan fluida hidrolik, dan checklist kelayakan unit tambang.' },
      { module: 'Simulasi Manuver & Teknik Penggalian Simulator 3D', hours: '40 Jam', description: 'Latihan skenario darurat, rem blong turunan curam, dan blind spot unit tambang di simulator modern.' },
      { module: 'Praktik Lapangan Excavator 30-Ton & Haul Truck 40-Ton', hours: '80 Jam', description: 'Operasi langsung bench loading, trenching parit air, stockpile dump, dan double side loading.' },
      { module: 'Radio Komunikasi Tambang & Aturan Pit Road Traffic', hours: '20 Jam', description: 'Standar panggilan darurat, right of way kendaraan berat, dan rambu-rambu pit tambang aktif.' },
      { module: 'Uji SIO Kemenaker RI & Asesmen Kompetensi', hours: '20 Jam', description: 'Uji kompetensi lapangan oleh Pengawas Ketenagakerjaan Kemenaker dan LSP.' },
    ],
  },
  {
    id: 'prog-k3',
    title: 'Pengawas Keselamatan Pertambangan (POP K3 Tambang)',
    category: 'KESELAMATAN',
    categoryTag: 'HSE',
    provider: 'Lembaga Diklat Profesi K3 & LSP ESDM',
    certType: 'Sertifikat Lisensi Pengawas Operasional Pertama (POP)',
    duration: '30 Hari • 120 Jam Pelatihan',
    funding: '100% Gratis (Dibiayai APBD Kab. Mimika)',
    quota: 25,
    remainingQuota: 5,
    coverImage: '/images/flyers/k3_tambang_flyer.jpg',
    description: 'Pembekalan regulasi keselamatan pertambangan Kaidah Teknik Pertambangan yang Baik sesuai Kepmen ESDM 1827 K, inspeksi bahaya, Job Safety Analysis (JSA), dan investigasi insiden lapangan.',
    targetIndustry: 'Seluruh Kontraktor & Pemegang IUP/IUPK Tambang di Mimika',
    benefits: ['Sertifikasi POP BNSP & Rekomendasi KTT', 'Buku Standar Regulasi ESDM 1827', 'Simulasi Lapangan Audit K3', 'Uang Saku & Uang Transport', 'Koneksi Langsung ke HR Dept Tambang'],
    isOpen: true,
    location: 'Auditorium Diklat Disnaker Kab. Mimika, SP2 Timika',
    batchNumber: 'Batch II / 2026',
    schedule: 'Senin - Jumat, 08.30 - 16.30 WIT',
    registrationDeadline: '10 Oktober 2026',
    requirements: [
      'WNI berdomisili di Kabupaten Mimika',
      'Pendidikan minimal D3 / S1 (Teknik) atau SMA/SMK dengan pengalaman kerja di area tambang min. 1 tahun',
      'Memiliki pemahaman dasar lingkungan kerja pertambangan',
      'Melampirkan surat rekomendasi / surat keterangan kerja (jika ada)',
      'Lolos seleksi wawancara komitmen pengawas K3',
    ],
    curriculum: [
      { module: 'Regulasi Keselamatan Pertambangan & Kepmen 1827 K', hours: '24 Jam', description: 'Tanggung jawab hukum Pengawas Operasional Pertama dan hierarki pengendali risiko tambang.' },
      { module: 'Penyusunan Job Safety Analysis (JSA) & Hiradc', hours: '28 Jam', description: 'Identifikasi potensi bahaya, matriks risiko, dan penetapan Standard Operating Procedure (SOP).' },
      { module: 'Teknik Inspeksi & Observasi Tugas Kerja (PTO)', hours: '24 Jam', description: 'Metode inspeksi area kerja kritis, behavior-based safety, dan audit kepatuhan APD.' },
      { module: 'Investigasi Kecelakaan Tambang & Root Cause Analysis', hours: '24 Jam', description: 'Pengamanan TKP, pengumpulan bukti, wawancara saksi, dan pelaporan form kecelakaan ke KTT/Inspektur.' },
      { module: 'Ujian Wawancara Asesor LSP ESDM', hours: '20 Jam', description: 'Uji sertifikasi kompetensi lisan dan portofolio langsung bersama Asesor Lisensi POP Nasional.' },
    ],
  },
  {
    id: 'prog-mek',
    title: 'Teknisi Mekanik Mesin & Pemeliharaan Pompa Hidrolik',
    category: 'MEKANIK',
    categoryTag: 'MECHANICAL',
    provider: 'Balai Latihan Kerja Mimika & Asosiasi Mekanik',
    certType: 'Sertifikat Kompetensi BNSP Teknisi Alat Berat',
    duration: '35 Hari • 140 Jam Pelatihan',
    funding: '100% Gratis (Dibiayai APBD Kab. Mimika)',
    quota: 25,
    remainingQuota: 9,
    coverImage: '/images/flyers/mekanik_flyer.jpg',
    description: 'Overhaul engine diesel putaran tinggi, diagnosa pompa dan sirkuit hidrolik, troubleshooting sistem transmisi mekanikal, dan pemeliharaan preventif workshop sentral pertambangan.',
    targetIndustry: 'Workshop Alat Berat, Bengkel Sentral Tambang, & Vendor Alat Berat',
    benefits: ['Tool-kit Mekanik Lengkap (Milik Peserta)', 'Sertifikat BNSP Teknisi Alat Berat', 'Praktik Mesin Diesel Caterpillar/Komatsu Asli', 'Uang Saku Bulanan', 'Asrama Gratis'],
    isOpen: true,
    location: 'Bengkel Mekanik Sentral BLK Mimika, Jl. Agimuga Mile 32',
    batchNumber: 'Batch III / 2026',
    schedule: 'Senin - Jumat, 08.00 - 16.00 WIT',
    registrationDeadline: '25 Oktober 2026',
    requirements: [
      'WNI berdomisili di Kabupaten Mimika (KTP Mimika)',
      'Usia 18 hingga 32 tahun',
      'Pendidikan minimal SMK Mesin/Otomotif atau SMA IPA/Sederajat',
      'Memiliki ketertarikan tinggi pada mesin berat dan mekanikal',
      'Sehat jasmani, bebas buta warna, siap kerja lapangan',
    ],
    curriculum: [
      { module: 'Fundamental Mesin Diesel 4-Tak & Common Rail', hours: '30 Jam', description: 'Prinsip kerja, pembongkaran kepala silinder, kalibrasi injektor, dan timing valve engine tambang.' },
      { module: 'Sistem Hidrolik Alat Berat & Pompa Axial Piston', hours: '35 Jam', description: 'Diagram skematik hidrolik, pengetesan tekanan sirkuit utama (main relief valve), dan ganti seal silinder.' },
      { module: 'Sistem Transmisi Power Shift & Final Drive', hours: '35 Jam', description: 'Torque converter, transmisi otomatis hidrolik, differential gear, dan perawatan undercarriage crawler.' },
      { module: 'Diagnostik Kerusakan & Electronic Control Module (ECM)', hours: '20 Jam', description: 'Penggunaan scanner diagnostik digital untuk membaca error code unit modern.' },
      { module: 'Asesmen Sertifikasi BNSP Teknisi Mekanik', hours: '20 Jam', description: 'Uji kompetensi teori dan praktik di hadapan Asesor Resmi BNSP bidang Alat Berat.' },
    ],
  },
  {
    id: 'prog-log',
    title: 'Manajemen Logistik Pergudangan & Rantai Pasok Kargo',
    category: 'LOGISTIK',
    categoryTag: 'LOGISTICS',
    provider: 'LSP Logistik Insan Prima & BLK Mimika',
    certType: 'Sertifikat BNSP Petugas Gudang & SIO Forklift',
    duration: '30 Hari • 120 Jam Pelatihan',
    funding: '100% Gratis (Dibiayai APBD Kab. Mimika)',
    quota: 25,
    remainingQuota: 7,
    coverImage: '/images/flyers/logistik_flyer.jpg',
    description: 'Manajemen inventori modern berbasis Warehouse Management System (WMS) digital, teknik penanganan material berbahaya (B3), operasi forklift 5 ton, dan logistik distribusi pelabuhan kargo.',
    targetIndustry: 'Terminal Pelabuhan Pomako, Gudang Material Sentral, & Forwarder Kargo',
    benefits: ['SIO Resmi Operator Forklift Kemenaker', 'Sertifikat Kompetensi BNSP Pergudangan', 'Asrama & Konsumsi Penuh', 'Uang Saku Pelatihan', 'Penyaluran Langsung ke Portsite'],
    isOpen: true,
    location: 'Warehouse Training Center BLK Pomako / Timika',
    batchNumber: 'Batch II / 2026',
    schedule: 'Senin - Jumat, 08.00 - 15.30 WIT',
    registrationDeadline: '18 Oktober 2026',
    requirements: [
      'WNI berdomisili di Kabupaten Mimika (KTP / KK Mimika)',
      'Usia 18 hingga 30 tahun',
      'Pendidikan minimal SMA / SMK Semua Jurusan',
      'Mampu mengoperasikan komputer dasar (Office / Data Entry)',
      'Sehat jasmani dan tidak buta warna',
    ],
    curriculum: [
      { module: 'Tata Kelola Gudang Modern & Software WMS', hours: '25 Jam', description: 'Inbound, racking, bin location, stock opname akurat, dan barcode scanning system.' },
      { module: 'Standar Penanganan & Penyimpanan Material Berbahaya (B3)', hours: '20 Jam', description: 'Katalog Safety Data Sheet (SDS), segregasi bahan kimia, spill response, dan APD kimia.' },
      { module: 'Pengoperasian Forklift Counterbalance & Reach Truck', hours: '45 Jam', description: 'Manuver ruang sempit, stacking palet rak bertingkat tinggi, dan inspeksi baterai forklift.' },
      { module: 'Logistik Intermoda & Regulasi Kargo Pelabuhan', hours: '15 Jam', description: 'Container lashing, dokumen bill of lading kargo laut dan kargo udara Bandara Mozes Kilangin.' },
      { module: 'Ujian Lisensi SIO Forklift & BNSP Logistik', hours: '15 Jam', description: 'Uji operasi forklift lapangan dan asesmen tertulis BNSP Pengelola Gudang.' },
    ],
  },
  {
    id: 'prog-elk',
    title: 'Teknisi Otomasi Elektrikal & Instrumentasi Industri',
    category: 'ELEKTRIKAL',
    categoryTag: 'ELECTRICAL',
    provider: 'Balai Latihan Kerja Mimika & LSP Elektrikal',
    certType: 'Sertifikat Kompetensi BNSP Teknisi Listrik Industri',
    duration: '35 Hari • 140 Jam Pelatihan',
    funding: '100% Gratis (Dibiayai APBD Kab. Mimika)',
    quota: 20,
    remainingQuota: 4,
    coverImage: '/images/flyers/elektrikal_flyer.jpg',
    description: 'Instalasi daya 3 fasa industri, wiring panel kendali motor (DOL & Star-Delta), pemrograman dasar PLC Siemens / Omron, kalibrasi sensor temperatur/tekanan, dan keselamatan bahaya Arc Flash.',
    targetIndustry: 'Pembangkit Listrik (Power Plant), Pabrik Smelter, & Kilang Konsentrator',
    benefits: ['Trainer Kit PLC & Multimeter Digital', 'Sertifikat Resmi BNSP Teknisi Listrik', 'Uang Saku Bulanan', 'Asrama Gratis', 'Jalur Penyerapan Kerja Industri'],
    isOpen: true,
    location: 'Laboratorium Otomasi BLK Mimika, Kuala Kencana',
    batchNumber: 'Batch I / 2026',
    schedule: 'Senin - Jumat, 08.00 - 16.00 WIT',
    registrationDeadline: '22 Oktober 2026',
    requirements: [
      'WNI berdomisili di Kabupaten Mimika (KTP Mimika)',
      'Usia 18 hingga 30 tahun',
      'Pendidikan minimal SMK Jurusan Listrik/Elektronika/Mekatronika atau SMA IPA',
      'Bebas dari buta warna total maupun parsial (wajib)',
      'Disiplin tinggi dan siap mematuhi aturan isolasi energi (LOTO)',
    ],
    curriculum: [
      { module: 'K3 Listrik & Prosedur Lockout-Tagout (LOTO)', hours: '15 Jam', description: 'Bahaya tegangan menengah/tinggi, eliminasi bahaya Arc Flash, dan standar isolasi energi aman.' },
      { module: 'Instalasi Tenaga 3 Fasa & Panel Distribusi Motor', hours: '40 Jam', description: 'Wiring kontaktor, thermal overload relay, push button kontrol, perakitan sirkuit Star-Delta.' },
      { module: 'Pemrograman PLC Dasar & Ladder Logic Diagram', hours: '45 Jam', description: 'Logika timer, counter, pengontrolan konveyor otomatis menggunakan PLC Siemens S7-1200.' },
      { module: 'Kalibrasi Sensor Suhu (RTD/TC) & Transmitter Tekanan', hours: '20 Jam', description: 'Loop testing sinyal analog 4-20mA, tuning controller PID industri, dan aktuator katup pneumatik.' },
      { module: 'Uji Sertifikasi BNSP Listrik Industri', hours: '20 Jam', description: 'Asesmen perakitan panel dan troubleshooting rangkaian listrik industri di hadapan Asesor BNSP.' },
    ],
  },
];
